# Generated by Django 3.2.9 on 2022-07-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0002_alter_cust_detals_sr_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_detals',
            name='Mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cust_detals',
            name='WeightG',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='cust_detals',
            name='WeightK',
            field=models.CharField(max_length=6),
        ),
    ]
